FROM nginx:1.25.3-alpine-slim

ENV TZ=Asia/Seoul

# ngin
COPY index.html /usr/share/nginx/html/index.html
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY font /usr/share/nginx/html/font
COPY img /usr/share/nginx/html/img
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
