apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-web
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-web
  template:
    metadata:
      labels:
        app: item-web
    spec:
      containers:
      - name: item-web
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: item-svc
  namespace: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30120
  selector:
    app: item-web
