apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-was
  namespace: backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-was
  template:
    metadata:
      labels:
        app: item-was
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: item-was
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: item-svc
  namespace: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: item-was
  type: ClusterIP
  clusterIP: 172.20.0.200
